# -*- coding: utf-8 -*-
"""DUNNO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jk7sJIuwP0PosB-qQGji2qXbfHIcLXCn
"""

pip install tensorflow


import streamlit as st
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
from PIL import Image

# Load the trained model
model_path = '/content/drive/MyDrive/Colab Notebooks/Final model h5 format/final_model.h5'
model = load_model(model_path)

def preprocess_image(image):
    image = image.resize((256, 256))
    image = image.convert("RGB")
    image = keras.preprocessing.image.img_to_array(image) / 255.0
    image = tf.expand_dims(image, axis=0)
    return image

def main():
    st.title("Shoe Classification")
    st.text("Upload an image for classification")

    uploaded_file = st.file_uploader("Choose an image", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption='Uploaded Image', use_column_width=True)

        processed_image = preprocess_image(image)

        # Make predictions
        class_names = ['class1', 'class2', 'class3']  # Update with your class names
        prediction = model.predict(processed_image)[0]
        predicted_class_index = tf.argmax(prediction).numpy()
        predicted_class = class_names[predicted_class_index]
        confidence = round(prediction[predicted_class_index] * 100, 2)

        st.success(f"Predicted Class: {predicted_class}")
        st.info(f"Confidence: {confidence}%")

if __name__ == "__main__":
    main()
